env:
  name: Canvas
  channels: 1
  size: 28
  n_denoising_steps: 50

experiment:
  n_epochs_reward_fn: 20
  batch_size_reward_fn: 128
  batch_size: 64
  use_replay_buffer: False
  replay_buffer_size: 1000
  validation_interval: 100
  resample_for_validation: True
  n_validation_samples: 10000
  full_gfn_retrain: 2
  use_gfn_z: True
  retrain_on_the_fly: True
  n_gt_trajs: 10000
