env:
  name: Grid
  ndim: 2
  height: 16
  nactions: 3

experiment:
  batch_size: 64
  batch_size_reward_fn: 128
  use_replay_buffer: False
  replay_buffer_size: 1000
  validation_interval: 100
  resample_for_validation: True
  n_validation_samples: 1000
  full_gfn_retrain: 2