env:
  name: Grid
  ndim: 2
  height: 8
  nactions: 3

experiment:
  n_epochs_reward_fn: 20
  batch_size_reward_fn: 128
  batch_size: 64
  use_replay_buffer: False
  replay_buffer_size: 1000
  validation_interval: 100
  resample_for_validation: True
  n_validation_samples: 10000
  full_gfn_retrain: 2
  use_gfn_z: True
  retrain_on_the_fly: True
  force_generate_dataset: False
  n_gt_trajs: 10000
  states_filename: 'sample_trajs_states.pkl'
  actions_filename: 'sample_trajs_actions.pkl'


baseline:
  n_epochs_reward_fn: 10
  batch_size_reward_fn: 512
  num_rollouts_per_epoch: 5


analysis:
  ndim: 2
  height: 8
